# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landr', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.ManyToManyField(to='landr.Register'),
        ),
    ]
